name: Odrive UI Deployment

env:
  TAG_NAME: ''

on:
  push:
    branches: [ master ]
    tags:
      - 'v1.0.0'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install odrive pyqtgraph pyqt5 pyqt6 pyinstaller
        shell: pwsh
      
  
      - name: Build odrivetool_UI application
        run: pyinstaller --onefile --windowed odrivetool_UI.py
        shell: pwsh

      - name: Extract tag name from ref
        id: get_tag_name
        run: |
          for tag in $(git tag --points-at HEAD); do
              if [[ " $tags " =~ " ${tag} " ]]; then
                  echo "::set-environment name=TAG_NAME::${tag}"
                  break
              fi
          done

      - name: Create Release
        
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
           Update notes for this release.
          draft: false
          prerelease: false


   
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/odrivetool_UI.exe
          asset_name: odrivetool_UI.exe
          asset_content_type: application/octet-stream


      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
