name: Odrive UI

on:
  push:
    branches: [ master ]  # 确保这与您的实际主分支名相匹配

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # 选择与您项目兼容的Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # development mode
          pip install odrive pyqtgraph pyqt5 pyqt6 pyinstaller  # 合并安装命令并确保包括pyinstaller

      - name: Create PyInstaller spec file
        run: echo "# odrive_ui" > odrive_ui.spec

      - name: Build application
        run: |
          pyinstaller --onefile --windowed odrive_ui.py
        shell: pwsh  # 指定 PowerShell 作为脚本的运行环境

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rsync -avz --exclude=__pycache__ ./dist/odrive_ui.exe odrive-ui@${{ secrets.HOST }}:/home/odrive-ui

      - name: Run application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            /home/odrive-ui/odrive_ui.exe
