name: Odrive UI Deployment

on:
  push:
    branches: [ master ]  

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # 安装 Python 依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install odrive pyqtgraph pyqt5 pyqt6 pyinstaller
        shell: pwsh

      # 使用 PyInstaller 构建 odrivetool_UI 应用
      - name: Build odrivetool_UI application
        run: pyinstaller --onefile --windowed odrivetool_UI.py
        shell: pwsh

      # 将应用程序部署到远程服务器
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rsync -avz --exclude=__pycache__ ./dist/odrivetool_UI.exe odrive-ui@${{ secrets.HOST }}:/home/odrive-ui
